language: c
compiler:
  - clang
  - gcc
script:
  - make clean && make build CFLAGS="-O3 -Wall -Werror -Wno-unused-label"
  - make clean && make run CFLAGS="-O3 -Wall -Werror -Wno-unused-label"
  - make clean && make generate CFLAGS="-O3 -Wall -Werror -Wno-unused-label"
# A nudge to avoid checking in broken builds.
notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - reagen@fas.harvard.edu
      - rdadolf@seas.harvard.edu
